### ISSUE TITLE
Welcome to CC, jennie!

### ISSUE THREAD

**Issue by mattl** [creativecommons/jennie-onboarding#1]
I made this little GitHub project as a sandbox of sorts, but also as a way to make sure we get you all the stuff you need.

You have a computer, IRC, email... let us know if there's anything else you want by making a GitHub issue... feel free to assign things to me, Mari or Eric, depending on who should handle it.

Remember all GitHub issues are public, so if you have any top-secret cookie recipes, send those via email.

**Comment by little-wow** [comment]
@mattl 
Not so secret cookie recipe: http://minimalistbaker.com/double-peanut-butter-chocolate-chip-cookies/
