### ISSUE TITLE
Tumblr Login?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/jennie-onboarding#11]
Can I have the login to CC Thing of the Day and http://creativecommons.tumblr.com/?

I'll ping Mari separately because these are private logins, but I'm logging this publicly.

**Comment by mmoreshead** [comment]
Invited you. You should create a tumblr account first I think, but maybe it prompts you.  Let me know.

**Comment by mattl** [comment]
Pretty sure you've been adding stuff, so I assume this can be closed
