### ISSUE TITLE
Jennie needs access to Civi & Litmus

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/jennie-onboarding#2]
login/password for each, pls

**Comment by mattl** [comment]
Litmus is all set.

**Comment by little-wow** [comment]
@mattl can I get a status update on Civi?  Hoping to ship an email today but can't do it without Civi access. thanks!

**Comment by mattl** [comment]
For today, hopefully Eric can assist in getting it out. I have a few other
things going on today...

**Comment by robmyers** [comment]
@little-wow I've created a user for you, it should have emailed the details to you. Ping me on irc if there are any problems.
