### ISSUE TITLE
Jennie needs access to Ascentis

### ISSUE THREAD

**Issue by ericsteuer** [creativecommons/jennie-onboarding#3]
Jennie needs an Ascentis login/pwd pls

**Comment by mmoreshead** [comment]
I can't give her access until I add her.  It's no my to-do for my return from DC.  Is there any kind of rush here?

**Comment by mmoreshead** [comment]
no = on

**Comment by ericsteuer** [comment]
no rush at all. if there's a way to designate that there's no rush when
filing these github issues (maybe i just write "there's no rush???" - i
dunno, don't fully understand how we use github yet), pls let me know.

On Mon, May 16, 2016 at 12:13 PM, Mari Moreshead <notifications@github.com>
wrote:

> no = on
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/jennie-onboarding/issues/3#issuecomment-219518233>
>



-- 
Invest in an open future. Support Creative Commons today:
http://bit.ly/19IjSKl

**Comment by mmoreshead** [comment]
Both a strength AND a weakness: I assume everyone needs everything immediately.

**Comment by mattl** [comment]
just do what i do... if an issue comes in from Eric, ignore it for a few months ;)

**Comment by ericsteuer** [comment]
#terrific

**Comment by mmoreshead** [comment]
@little-wow Did two things that *should* have triggered an email to login.  Let me know if not.
