### ISSUE TITLE
Please make a CCID

### ISSUE THREAD

**Issue by mattl** [creativecommons/jennie-onboarding#4]
CCID is our centralized login mechanism for a bunch of things. Please make one for your CC email address, and let me know when you're done and I'll add you to some stuff...

**Comment by little-wow** [comment]
I made one

**Comment by mattl** [comment]
Please confirm if you're able to login to Teamspace by adding yourself here https://teamspace.creativecommons.org/Contact_Info

**Comment by little-wow** [comment]
yes, I am able to log into Teamspace.

**Comment by little-wow** [comment]
And I added myself to "staff"
