### ISSUE TITLE
CC blog access

### ISSUE THREAD

**Issue by mattl** [creativecommons/jennie-onboarding#6]

**Comment by little-wow** [comment]
Just a ping to escalate this to high priority if possible :)

**Comment by mattl** [comment]
Waiting on confirmation of #4

**Comment by mattl** [comment]
Please visit https://blog.creativecommons.org/wp-admin/ and login with your CCID.

**Comment by little-wow** [comment]
@mattl I don't appear to have posting privileges.

**Comment by mattl** [comment]
All set now.
