### ISSUE TITLE
Can I have access to create a repository?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/jennie-onboarding#8]
Hey @mattl I would love to store assets I'm creating in a repo but I appear not to have enough privileges.

Thanks!

**Comment by mattl** [comment]
If you tell me the name of the project, I can make you one.

**Comment by little-wow** [comment]
Two:
1. Emails
2. Images

**Comment by mattl** [comment]
They can probably live in a single repo, generally "communications" or something?

**Comment by little-wow** [comment]
Sure, that's fine.

**Comment by mattl** [comment]
https://github.com/creativecommons/communications/
