### ISSUE TITLE
Google Analytics access?

### ISSUE THREAD

**Issue by little-wow** [creativecommons/jennie-onboarding#9]
Hey @mattl do we have Google Analytics? If we do, can I have access to it?

**Comment by mattl** [comment]
![screenshot from 2016-05-20 11-30-45](https://cloud.githubusercontent.com/assets/33296/15434795/51446274-1e7e-11e6-9163-5e545269cf29.png)

Will try again on Monday

**Comment by little-wow** [comment]
@mattl Could you try again? ty!
